### ISSUE TITLE
RX 580 is not showing correct framebuffer.

### ISSUE THREAD

**Issue by kirankumarsripati** [rafaelmaeuer/Asus-P8P67Pro-Hackintosh#13]
Hi, 

I have similar specs like yours - ASUS P8P67 PRO Mainboard with an Intel Core i7 2600K Processor and 16GB RAM. A GeForce GTX 710 and Radeon RX 580 graphics card. Both the cards are detected, but I am getting output from GTX 710 only.

![Screenshot 2020-09-27 at 12 30 49 PM](https://user-images.githubusercontent.com/856090/94358255-59c78900-00bd-11eb-99b4-f538decfa12e.png)

For RX 580, it should show FrameBuffer as Orinoco, I tried multiple ways, but still I am not able to figure out. How did you manage to run RX 570?

It would be a great, If I get any help on this.
https://github.com/kirankumarsripati/Asus-P8P67Pro-Unbeast-10/tree/whatever

Thanks in Advance.

**Comment by rafaelmaeuer** [comment]
Hey, usually RX 570 should work ootb... 
Do you use WEG-kext?
Have you tried to boot with a single card only?
To which PCI-slot is your card connected?

**Comment by kirankumarsripati** [comment]
Hi @rafaelmaeuer,

I removed GTX710 and RX 580 is connected in Slot 1. I am using WEG-kext with Lilu.kext. I am able to access using Remote Desktop, my screen is blank.

<img width="588" alt="Screenshot 2020-09-30 at 8 32 49 PM" src="https://user-images.githubusercontent.com/856090/94703631-ad0b3700-035c-11eb-93a5-277f04e79043.png">

<img width="1014" alt="Screenshot 2020-09-30 at 8 34 18 PM" src="https://user-images.githubusercontent.com/856090/94703662-b4324500-035c-11eb-9d07-494d51e90594.png">

**Comment by rafaelmaeuer** [comment]
Okay - which connectors do you use?
I remember there are problems with the DVI-connectros with these cards.
Try to go into sleep mode, wake up the hack and see if it changes something?
Otherwise I recommend to use HDMI/DP-Connectors with this card.

Otherwise check these topics:
https://www.tonymacx86.com/threads/rx570-dual-display-not-working.247978/
https://www.hackintosh-forum.de/forum/thread/39490-msi-radeon-rx560-und-3-monitore-dvi-bleibt-schwarz/
https://www.hackintosh-forum.de/forum/thread/33044-black-screen-fix-f%C3%BCr-amd-karten/
https://www.hackintosh-forum.de/forum/thread/36549-amd-rx580-high-sierra-trippelscreen/
https://www.tonymacx86.com/threads/radeon-rx-560-on-10-13-4-macos-high-sierra.249235/

**Comment by kirankumarsripati** [comment]
@rafaelmaeuer 
After trying multiple ways, now I was able to fix the black screen issue by using the adapter HDMI to Display Port.
https://www.amazon.in/gp/product/B018X4DMU4/
